on:
  push:
    tags:
      - '**'
  workflow_dispatch:

name: Build tagged releases
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
          os:
            - linux-x64
            - osx-arm64
            - osx-x64
            - win-x64
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Create publish package
        run: dotnet publish -c Release -r ${{matrix.os}} --self-contained -warnaserror osu.Desktop.slnf

      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}
          path: osu.Desktop/bin/Release/net8.0/${{matrix.os}}

  release:
    name: Release
    needs: build
    runs-on: Ubuntu-latest
    steps:
      - name: restore release .zip
        uses: actions/cache/restore@v4
        with:
          path: ${{matrix.os}}.zip
          key: ${{ matrix.os }}-${{ github.sha }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
#        with:
#          merge-multiple: true
        if: startsWith(github.ref, 'refs/tags/')

      - name: zip releases
        run: |
          for directory in */
          do
            zip -r "$directory.zip" "$directory"
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip
