on:
  push:
    tags:
      - '**'
  workflow_dispatch:

name: Build tagged releases
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    name: Build
    runs-on: Ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
          os:
            - linux-x64
            - osx-arm64
            - osx-x64
            - win-x64
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Create publish package
        run: dotnet publish -c Release -r ${{matrix.os}} --self-contained -warnaserror osu.Desktop.slnf

      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}
          path: osu.Desktop/bin/release/net8.0/${{matrix.os}}
